apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment 
  labels:
    app: myservice
    type: deploycontrol 
spec:
  template:
    metadata:
      name: myapp-prod
      labels:
        app: myapp
        type: backend
    spec:
      containers:
      - name: sample-service-pod
        image: "simplenodeapi:2"
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        env:
        - name: SERVICE_NAME
          value: "SampleServiceB"
        ports:
          - containerPort: 3000
            name: http
  replicas: 3
  selector:
    matchLabels:
      type: backend
