apiVersion: v1
kind: Pod
metadata:
  name: "sample-service-pod"
  namespace: default
  labels:
    app: "sample-service-pod"
spec:
  containers:
  - name: sample-service-pod
    image: "simplenodeapi:2"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
    - name: SERVICE_NAME
      value: "SampleServiceA"
      # valueFrom:
      #   configMapKeyRef:
      #     name: myapp
      #     key: DB_HOST
    ports:
    - containerPort: 3000
      name: http
    volumeMounts:
    - name: localtime
      mountPath: /etc/localtime
  volumes:
    - name: localtime
      hostPath:
        path: /usr/share/zoneinfo/Asia/Calcutta
  restartPolicy: Always
---
