apiVersion: v1
kind: PersistentVolume
metadata:
  name: commonfspv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/docker"
